# Generated by Django 5.1.4 on 2024-12-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_salesrepresentative_team_customer_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='sales_representatives',
        ),
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
